name = "axis7818 windows dotfiles"
description = "axis7818 dotfiles for windows"

[vars]
me.first_name = "Cameron"
me.last_name = "Taylor"

# Git
[[files]]
template = "git\\gitconfig"
target = "~\\.gitconfig"
tags = ["git"]
[[files]]
template = "lazygit\\config.yml"
target = "C:\\Users\\axis7818\\AppData\\Local\\lazygit\\config.yml"
tags = ["git"]
